on:
    workflow_call:
      inputs: {}

jobs:
  publish-to-nuget:
    name: >-
      Publish Packages to nuget.org
    runs-on: ubuntu-latest
    environment:
      name: nuget
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: nuget-artifact-linux-amd64 
        path: ${{ github.workspace }}

    - name: Push generated package to nuget.org
      run: dotnet nuget push *.nupkg -s ${{ github.workspace }} --skip-duplicate --no-symbols true -k "${{secrets.NUGET_API}}"
